server:
  servlet:
    context-path: /xxgl
  port: 8086
mybatis:
  typeAliasesPackage: com.mf.demo.*.model
  mapperLocations: classpath:mapper/*/*Mapper.xml
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/xxgl?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123@qwe
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
logging:
  level:
    #防止启动springboot项目报CONDITIONS EVALUATION REPORT
    org.springframework.boot.autoconfigure: error
    com.mf.demo.*.dao: debug
  config: xxgl/src/main/resources/logback.xml